// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL5WjiIeBqSDe9qHVMQUyjh4hkU1Vinv4',
    appId: '1:815239986420:web:d45cf1e9a8cbbc00c332a1',
    messagingSenderId: '815239986420',
    projectId: 'x-password-616i08',
    authDomain: 'x-password-616i08.firebaseapp.com',
    storageBucket: 'x-password-616i08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxHTLFET5Ev5U9tzdufuvGTuKRmvgacq0',
    appId: '1:815239986420:android:814755f88383b472c332a1',
    messagingSenderId: '815239986420',
    projectId: 'x-password-616i08',
    storageBucket: 'x-password-616i08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYyYomMHecckqqHyR1HO0phwrkPG0mzWw',
    appId: '1:815239986420:ios:c0838a142859c58bc332a1',
    messagingSenderId: '815239986420',
    projectId: 'x-password-616i08',
    storageBucket: 'x-password-616i08.appspot.com',
    androidClientId: '815239986420-e080uq04up47s65a2p42002pob47pg19.apps.googleusercontent.com',
    iosClientId: '815239986420-d748f4oaq1uamll3pucef4q2g0gkhd7l.apps.googleusercontent.com',
    iosBundleId: 'com.xmartandroid.xpassword',
  );
}
